#!/bin/bash

# Restaurant HORECA App - Automated Setup Script
# This script automates the complete setup after cloning the repository

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Restaurant HORECA App - Setup Script${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Check if Node.js is installed
if ! command -v node &> /dev/null; then
    echo -e "${RED}Error: Node.js is not installed!${NC}"
    echo "Please install Node.js version 18 or higher from https://nodejs.org/"
    exit 1
fi

NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 18 ]; then
    echo -e "${RED}Error: Node.js version 18 or higher is required!${NC}"
    echo "Current version: $(node -v)"
    exit 1
fi

echo -e "${GREEN}✓ Node.js $(node -v) detected${NC}"

# Check if npm is installed
if ! command -v npm &> /dev/null; then
    echo -e "${RED}Error: npm is not installed!${NC}"
    exit 1
fi

echo -e "${GREEN}✓ npm $(npm -v) detected${NC}"
echo ""

# Check if git-lfs is installed and pull LFS files
echo -e "${BLUE}Step 0: Pulling Git LFS files...${NC}"
if command -v git-lfs &> /dev/null; then
    echo -e "${YELLOW}Git LFS detected, pulling files...${NC}"
    git lfs install > /dev/null 2>&1 || true
    git lfs pull > /dev/null 2>&1 || echo -e "${YELLOW}Warning: Some LFS files might not be available${NC}"
    echo -e "${GREEN}✓ Git LFS files pulled${NC}"
else
    echo -e "${YELLOW}⚠ Git LFS not installed - package.json files might be LFS pointers${NC}"
    echo -e "${YELLOW}  Install Git LFS from: https://git-lfs.github.com/${NC}"
    echo -e "${YELLOW}  Then run: git lfs install && git lfs pull${NC}"
    echo ""
fi

# Navigate to server directory
cd restaurant_app_v3_translation_system/server

echo -e "${BLUE}Step 1: Setting up environment configuration...${NC}"

# Create .env file if it doesn't exist
if [ ! -f .env ]; then
    echo -e "${YELLOW}Creating .env file from defaults...${NC}"
    cat > .env << 'EOF'
# Restaurant HORECA App - Environment Configuration
# Auto-generated by setup script

# Server Configuration
NODE_ENV=development
PORT=3001
TZ=Europe/Bucharest

# Database Configuration
DATABASE_PATH=./restaurant.db

# Session Configuration
SESSION_SECRET=$(openssl rand -hex 32)

# Optional: Queue Configuration (uncomment if using Redis)
# REDIS_URL=redis://127.0.0.1:6379

# Optional: API Configuration
# API_BASE=http://localhost:3001
EOF
    echo -e "${GREEN}✓ .env file created with default values${NC}"
else
    echo -e "${GREEN}✓ .env file already exists${NC}"
fi

echo ""
echo -e "${BLUE}Step 2: Installing backend dependencies...${NC}"
echo -e "${YELLOW}This may take a few minutes...${NC}"

npm install --legacy-peer-deps

echo -e "${GREEN}✓ Backend dependencies installed${NC}"
echo ""

echo -e "${BLUE}Step 3: Installing frontend (admin-vite) dependencies...${NC}"

cd admin-vite

npm install --legacy-peer-deps

echo -e "${GREEN}✓ Frontend dependencies installed${NC}"
echo ""

echo -e "${BLUE}Step 4: Building frontend application...${NC}"

npm run build

echo -e "${GREEN}✓ Frontend built successfully${NC}"
echo ""

# Go back to server directory
cd ..

echo -e "${BLUE}Step 5: Database initialization...${NC}"
echo -e "${YELLOW}Database will be automatically initialized on first server start${NC}"
echo -e "${GREEN}✓ Database setup configured${NC}"
echo ""

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Setup Complete! 🎉${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo -e "${BLUE}Next steps:${NC}"
echo ""
echo "1. Start the development server:"
echo -e "   ${YELLOW}cd restaurant_app_v3_translation_system/server${NC}"
echo -e "   ${YELLOW}npm start${NC}"
echo ""
echo "2. For development with hot-reload:"
echo -e "   ${YELLOW}Terminal 1: cd restaurant_app_v3_translation_system/server && npm start${NC}"
echo -e "   ${YELLOW}Terminal 2: cd restaurant_app_v3_translation_system/server/admin-vite && npm run dev${NC}"
echo ""
echo "3. Access the application:"
echo -e "   ${YELLOW}Admin Panel: http://localhost:3001/admin-vite/${NC}"
echo -e "   ${YELLOW}Legacy Admin: http://localhost:3001/admin.html${NC}"
echo ""
echo -e "${BLUE}For production deployment:${NC}"
echo -e "   ${YELLOW}NODE_ENV=production npm start${NC}"
echo ""
echo -e "${GREEN}Happy coding! 🚀${NC}"
