@echo off
REM Restaurant HORECA App - Automated Setup Script (Windows)
REM This script automates the complete setup after cloning the repository

echo ========================================
echo Restaurant HORECA App - Setup Script
echo ========================================
echo.

REM Check if Node.js is installed
where node >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo Error: Node.js is not installed!
    echo Please install Node.js version 18 or higher from https://nodejs.org/
    pause
    exit /b 1
)

echo [OK] Node.js detected
node -v

REM Check if npm is installed
where npm >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo Error: npm is not installed!
    pause
    exit /b 1
)

echo [OK] npm detected
npm -v
echo.

REM Check if git-lfs is installed and pull LFS files
echo Step 0: Pulling Git LFS files...
where git-lfs >nul 2>nul
if %ERRORLEVEL% EQU 0 (
    echo Git LFS detected, pulling files...
    git lfs install >nul 2>nul
    git lfs pull >nul 2>nul
    echo [OK] Git LFS files pulled
) else (
    echo [WARNING] Git LFS not installed - package.json files might be LFS pointers
    echo           Install Git LFS from: https://git-lfs.github.com/
    echo           Then run: git lfs install ^&^& git lfs pull
    echo.
)

REM Navigate to server directory
cd restaurant_app_v3_translation_system\server

echo Step 1: Setting up environment configuration...

REM Create .env file if it doesn't exist
if not exist .env (
    echo Creating .env file from defaults...
    (
        echo # Restaurant HORECA App - Environment Configuration
        echo # Auto-generated by setup script
        echo.
        echo # Server Configuration
        echo NODE_ENV=development
        echo PORT=3001
        echo TZ=Europe/Bucharest
        echo.
        echo # Database Configuration
        echo DATABASE_PATH=./restaurant.db
        echo.
        echo # Session Configuration
        echo SESSION_SECRET=INSECURE_DEFAULT_CHANGE_ME_IN_PRODUCTION_%RANDOM%%RANDOM%%RANDOM%
        echo.
        echo # Optional: Queue Configuration (uncomment if using Redis^)
        echo # REDIS_URL=redis://127.0.0.1:6379
        echo.
        echo # Optional: API Configuration
        echo # API_BASE=http://localhost:3001
    ) > .env
    echo [OK] .env file created with default values
) else (
    echo [OK] .env file already exists
)

echo.
echo Step 2: Installing backend dependencies...
echo This may take a few minutes...

call npm install --legacy-peer-deps
if %ERRORLEVEL% NEQ 0 (
    echo Error installing backend dependencies!
    pause
    exit /b 1
)

echo [OK] Backend dependencies installed
echo.

echo Step 3: Installing frontend (admin-vite^) dependencies...

cd admin-vite

call npm install --legacy-peer-deps
if %ERRORLEVEL% NEQ 0 (
    echo Error installing frontend dependencies!
    pause
    exit /b 1
)

echo [OK] Frontend dependencies installed
echo.

echo Step 4: Building frontend application...

call npm run build
if %ERRORLEVEL% NEQ 0 (
    echo Error building frontend!
    pause
    exit /b 1
)

echo [OK] Frontend built successfully
echo.

REM Go back to server directory
cd ..

echo Step 5: Database initialization...
echo Database will be automatically initialized on first server start
echo [OK] Database setup configured
echo.

echo ========================================
echo Setup Complete! 🎉
echo ========================================
echo.
echo Next steps:
echo.
echo 1. Start the development server:
echo    cd restaurant_app_v3_translation_system\server
echo    npm start
echo.
echo 2. For development with hot-reload:
echo    Terminal 1: cd restaurant_app_v3_translation_system\server ^&^& npm start
echo    Terminal 2: cd restaurant_app_v3_translation_system\server\admin-vite ^&^& npm run dev
echo.
echo 3. Access the application:
echo    Admin Panel: http://localhost:3001/admin-vite/
echo    Legacy Admin: http://localhost:3001/admin.html
echo.
echo For production deployment:
echo    set NODE_ENV=production ^&^& npm start
echo.
echo Happy coding! 🚀
echo.

pause
